### ISSUE TITLE
Grid bottom border is missing from column header

### ISSUE THREAD

**Issue by igDivya** [IgniteUI/igniteui-wc-examples#594] opened 2023-11-16 21:26 UTC
1)Run any sample 

https://staging.infragistics.com/webcomponents-demos/samples/grids/grid/action-strip
https://staging.infragistics.com/webcomponents-demos/samples/grids/grid/data-searching

2)Select filtering option of any column and notice 

issue: Bottom Border is missing from the column

![image](https://github.com/IgniteUI/igniteui-wc-examples/assets/22081100/6c9809e7-7a3b-4fac-ab55-1b3a805cf7b9)

**Comment by skrustev** [comment] 2023-11-21 08:34
@IgDivya Can you elaborate more or highlight which border you mean, because to me looks like its expected.

**Comment by igDivya** [comment] 2023-11-21 15:59
Was talking about missing blue border .
![missingBottomBorder](https://github.com/IgniteUI/igniteui-wc-examples/assets/22081100/b853375f-eeed-42c1-90b8-0836f3fafb84)

**Comment by skrustev** [comment] 2023-11-22 08:57
Oh ok, then this is expected, because the filtering row is showing for that column and the column can be switched that the row corresponds. Marking this as not a bug.

**Closed** 2023-11-22 08:59 UTC
Labels: bug: not-a-bug
