### ISSUE TITLE
Dock manager styling sample text flowing out

### ISSUE THREAD

**Issue by zhosti** [IgniteUI/igniteui-wc-examples#99] opened 2021-10-07 08:44 UTC
In [Dock Manager Styling](https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/dock-manager#styling) sample, text in the `Global Electricity Demand` chart is flowing out. of the pane.

![Screenshot 2021-10-07 114222](https://user-images.githubusercontent.com/7760119/136350510-b6f7f98c-3643-4a8f-b6f2-3eb96ece543b.png)

**Comment by gedinakova** [comment] 2021-11-02 12:33
Duplicate of #118

**Closed** 2021-11-02 12:33 UTC
Labels: is: duplicate, area: bug
